config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :reports
  # get 'home/index'
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends

         def reports
          Report.where(user_id: self.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show; end

  # GET /reports/new
  def new
    #@report = Report.new
    @report = current_user.reports.build
  end

  # GET /reports/1/edit
  def edit; end

  # POST /reports or /reports.json
  def create
    #@report = Report.new(report_params)
    @report = current_user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to report_url(@report), notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @report = current_user.reports.find_by(id: params[:id])
    redirect_to reports_path, notice: "Not Authorized To Edit This Report" if @report.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def report_params
    params.require(:report).permit(:date_of_incident, :time_of_incident, :type_of_incident, :location_of_incident,
                                   :initiator_of_incident, :unit_identity, :details_of_incident, :action_taken, :incident_status, :further_information, :signed_by, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Reports App', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "About", home_about_path, class: "nav-link" %>  
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Reports", reports_path, class: "nav-link" %>  
          </li>
          <li class="nav-item">
            <%= link_to "Add Report", new_report_path, class: "nav-link" %>  
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>  
          </li>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>  
          </li>

        <% else %>

          <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>  
          </li>

          <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>  
          </li>

        <% end %>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Reports Application</h1>

<p>This is a Ruby on Rails application developed by First lieutenant Federico N. Sapuppo,
from the Argentinian Air Force, in order to provide a simple and fast way to upload
Immediate Reports already transmitted by radio or phone, in the context of the 
UNFICYP mission.</p></br>

<h2>How to fill up the forms</h2></br>

<h3>A) Date of Incident</h3>

<p>Fill up the date in wich the incident took place. e.g.: 05/18/2023</p>

<h3>B) Time of Incident</h3>

<p>Fill up the time in wich the incident took place. e.g.: 08:30hs</p>

<h3>C) Type of Incident</h3>

<p>Fill up the type of incident. e.g.: Traffic accident</p>

<h3>D) Location of Incident</h3>

<p>Fill up with information about near UN or oposing forces positions, and 
with the exact location in wich the incident took place. Preffer the use of
the Military Grid Reference System (MGRS). If not possible, use UTM system and
specify the refference system used. e.g.: 
<ul>
<li>MGRS 36S WD 13246 71090 </li>
<li>UTM Lat: 34.9823018 N, Long: 33.1451285 E </li>
<li>UTM Lat: 34° 58&#39 56&quot N, Long: 33° 8&#39 42&quot E </li>
</ul>
</p>

<h3>E) Initiator of Incident</h3>Allways

<p>Fill up the initiator of incident. Use the most precise abbreviation. 
Use this refference for choosing the most appropriate abbreviation:
<ul>
<li>TF for Turkish Forces</li>
<li>NG for National Guard</li>
<li>TkCyp for Turkish Cypriots</li>
<li>GkCyp for Greek Cypriots</li>
<li>CYPOL for Cyprus Police</li>
<li>UN for United Nations personnel</li>
<li>Civ for Unidentify Civilians or tourists</li>
<li>Other for Unidentify Initiators (use this only as a last resort)</li>
</ul>
</p>

<h3>F) Unit Identity</h3>

<p>Fill up the unit identity, only if military (battalion, brigade, or division UI).
e.g.: MTSA 1432213</p>

<h3>G) Details of Incident</h3>

<p>Fill up the details of the incident being presice and providing as much information
as possible. Try answering the following questions: who, what, when, where, why and how.</p>

<h3>H) Actions taken by UNFICYP</h3>

<p>Fill up explaining the actions taken by the U.N. personnel present at the time of the incident</p>

<h3>I) Incident Status</h3>

<p>Fill up just either &quoton-going&quot or &quotclosed&quot</p>

<h3>J) Any further information</h3>

<p>Fill up any further information such as past incidents related to the one being reported,
witnesses&#39 contact information, and links to multimedia like photos and video recordings.</p>

<h3>J) Signed by</h3>

<p>Fill up your abbreviated military rank, family name, name, and abbreviated force, to wich you belong,
 in that order.
e.g.: 1LT Sapuppo, Federico. AAF.
<br><br>
For ranks, use the following abbreviations:

<br><br>Army<br>
<ul>
<li>1) SLT for Sub Lieutenant</li>
<li>2) LT for Lieutenant</li>
<li>3) 1LT for First Lieutenant</li>
<li>4) CPT for Captain</li>
<li>5) MAJ for Major</li>
<li>6) LTC for Lieutenant Colonel</li>
<li>7) COL for Colonel</li>
<li>8) COLM for Colonel Major</li>
<li>9) BG for Brigadier General</li>
<li>10) DG for Division General</li>
<li>11) LTG for Lieutenant General</li>
</ul>

<br>Navy<br><br>
<ul>
<li>1) GN for Guards of the Navy</li>
<li>2) CL for Corvette Lieutenant</li>
<li>3) FL for Frigate Lieutenant</li>
<li>4) SL for Ship Lieutenant</li>
<li>5) CC for Corvette Captain</li>
<li>6) FC for Frigate Captain</li>
<li>7) SC for Ship Captain</li>
<li>8) NC for Navy Commodore</li>
<li>9) CA for Counter Admiral</li>
<li>10) VA for Vice Admiral</li>
<li>11) AD for Admiral</li>
</ul>

<br>Air Force<br><br>
<ul>
<li>1) EN for Ensign</li>
<li>2) LT for Lieutenant</li>
<li>3) 1LT for First Lieutenant</li>
<li>4) CPT for Captain</li>
<li>5) MAJ for Major</li>
<li>6) VC for Vice Commodore</li>
<li>7) COM for Commodore</li>
<li>8) COMM for Commodore Major</li>
<li>9) B for Brigadier</li>
<li>10) BM for Brigadier Major</li>
<li>11) BG for Brigadier General</li>
</ul>

Use the following abbreviations for forces:
<br><br>
<ul>
<li>AA for Argentinian Army</li>
<li>AN for Argentinian Navy</li>
<li>AAF for Argentinian Air Force</li>
</ul>

</p>

app/views/home/index.html.erb
<h1>Add a New Report!</h1>

<p>Go to "About" for information about how to fill up reports.</p>

<% if user_signed_in? %>
<%= link_to "New report", new_report_path, class:"btn btn-dark" %>
<% else %>
<p> You need to sing in in order to add, see, or delete reports! <p>
<%= link_to "SIGN IN!", new_user_session_path, class:"btn btn-dark" %>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Reports</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
  <body>

    <%= render 'home/header' %>  
    <div class="container">
    </br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <%= yield %>
    </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>
      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :date_of_incident, style: "display: block", class:"form-label" %>
    <%= form.date_field :date_of_incident, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :time_of_incident, style: "display: block", class:"form-label" %>
    <%= form.time_field :time_of_incident, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :type_of_incident, style: "display: block", class:"form-label" %>
    <%= form.text_field :type_of_incident, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :location_of_incident, style: "display: block", class:"form-label" %>
    <%= form.text_field :location_of_incident, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :initiator_of_incident, style: "display: block", class:"form-label" %>
    <%= form.text_field :initiator_of_incident, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :unit_identity, style: "display: block", class:"form-label" %>
    <%= form.text_field :unit_identity, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :details_of_incident, style: "display: block", class:"form-label" %>
    <%= form.text_field :details_of_incident, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :action_taken, style: "display: block", class:"form-label" %>
    <%= form.text_field :action_taken, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :incident_status, style: "display: block", class:"form-label" %>
    <%= form.text_field :incident_status, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :further_information, style: "display: block", class:"form-label" %>
    <%= form.text_field :further_information, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :signed_by, style: "display: block", class:"form-label" %>
    <%= form.text_field :signed_by, class:"form-control" %>
  </div>
  <div class="field form-group">
    <% form.label :signed_by, style: "display: block", class:"form-label" %>
    <%= form.number_field :user_id, id: :report_user_id, class:"form-control", 
    value:current_user.id, type: :hidden %>
  </div>
  <br>
  <div>
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
  <p>
    <strong>Date of incident:</strong>
    <%= report.date_of_incident %>
  </p>
  <p>
    <strong>Time of incident:</strong>
    <%= report.time_of_incident.strftime("%k:%M") %>
  </p>
  <p>
    <strong>Type of incident:</strong>
    <%= report.type_of_incident %>
  </p>
  <p>
    <strong>Location of incident:</strong>
    <%= report.location_of_incident %>
  </p>
  <p>
    <strong>Initiator of incident:</strong>
    <%= report.initiator_of_incident %>
  </p>
  <p>
    <strong>Unit identity:</strong>
    <%= report.unit_identity %>
  </p>
  <p>
    <strong>Details of incident:</strong>
    <%= report.details_of_incident %>
  </p>
  <p>
    <strong>Action taken:</strong>
    <%= report.action_taken %>
  </p>
  <p>
    <strong>Incident status:</strong>
    <%= report.incident_status %>
  </p>
  <p>
    <strong>Further information:</strong>
    <%= report.further_information %>
  </p>
  <p>
    <strong>Signed by:</strong>
    <%= report.signed_by %>
  </p>
  <p>
    <% report.user_id %>
  </p>
</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report, class:"btn btn-secondary" %> |
  <%= link_to "Back to reports", reports_path, class:"btn btn-secondary" %>
</div>

app/views/reports/index.html.erb
<h1>Reports List</h1>

<div id="reports">
  <% @reports.each do |report| %>
    <%= render report %>
    <p>
      <%= link_to "Show this report", report, class:"btn btn-secondary" %>
    </p>
  <% end %>
</div>

<%= link_to "New report", new_report_path, class:"btn btn-dark" %>

app/views/reports/new.html.erb
<h1>Add New Report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Back to reports", reports_path, class:"btn btn-secondary"%>
</div>

app/views/reports/show.html.erb
<div class="jumbotron">
  <h1 class="display-3">Report: <%= @report.date_of_incident %> | <%= @report.time_of_incident.strftime("%k:%M") %></h1>
  <p class="lead"><%= render @report %></p>
  <hr class="my-2">
  <p class="lead">
    <%= link_to "Back to reports", reports_path, class:"btn btn-dark" %>
    <% if @report.user == current_user %>
      <%= link_to "Edit this report", edit_report_path(@report), class:"btn btn-warning" %> |
      <%= button_to "Destroy this report", @report, method: :delete, class:"btn btn-danger" %>
    <% end %>
  </p>
</div>